# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20170315_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unrated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
            ],
        ),
    ]
