# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movieinfo_imdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('movieId', models.IntegerField()),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
