# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_ratings2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('movieId', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
