# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_ummat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageIndex', models.IntegerField()),
                ('ageVal', models.IntegerField()),
                ('ageRange', models.CharField(max_length=10)),
                ('movieId', models.IntegerField()),
                ('count1', models.IntegerField()),
                ('count2', models.IntegerField()),
                ('count3', models.IntegerField()),
                ('count4', models.IntegerField()),
                ('count5', models.IntegerField()),
                ('avgRating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GenderAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genderIndex', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('movieId', models.IntegerField()),
                ('count1', models.IntegerField()),
                ('count2', models.IntegerField()),
                ('count3', models.IntegerField()),
                ('count4', models.IntegerField()),
                ('count5', models.IntegerField()),
                ('avgRating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JobAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.IntegerField()),
                ('job', models.CharField(max_length=100)),
                ('movieId', models.IntegerField()),
                ('count1', models.IntegerField()),
                ('count2', models.IntegerField()),
                ('count3', models.IntegerField()),
                ('count4', models.IntegerField()),
                ('count5', models.IntegerField()),
                ('avgRating', models.FloatField()),
            ],
        ),
    ]
