# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0008_ageavg_genderavg_jobavg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1, max_length=100)),
                ('profession', models.CharField(choices=[(1, 'Student'), (2, 'Lawyer'), (3, 'Womaniser')], default=1, max_length=100)),
                ('country', models.CharField(choices=[(1, 'India'), (2, 'Zimbabwe'), (3, 'New Zealand'), (4, 'USA')], default=1, max_length=100)),
                ('image', models.FileField(upload_to='images/')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
