# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20170424_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='u_id',
        ),
    ]
