# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20170424_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trained',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=100),
        ),
    ]
