# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20170425_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
